version: '3.8'

services:
  couchdb:
    build: ./birthday-couchdb/Containerimage
    volumes:
      - couchdb_data:/opt/couchdb/data
    environment:
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
    networks:
      - mein-netzwerk

  meine-flask-app:
    build: .
    depends_on:
      - couchdb
    ports:
      - "8001:8001"
    environment:
      COUCHDB_URL: http://couchdb:5984
      COUCHDB_DB: birthday_db
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      FLASK_RUN_PORT: 8001
    networks:
      - mein-netzwerk

networks:
  mein-netzwerk:

volumes:
  couchdb_data:
