apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001
    name: http
  selector:
    app: flask-app
